// src/App.svelte
<script>
  import resumeData from "./resumeData.json";
  import Header from "./components/Header.svelte";
  import Summary from "./components/Summary.svelte";
  import Experience from "./components/Experience.svelte";
  import Education from "./components/Education.svelte";
  import Skills from "./components/Skills.svelte";
</script>
<main>
  <Header name={resumeData.name} title={resumeData.title} contact={resumeData.contact} />
  <Summary summary={resumeData.summary} />
  <Skills skills={resumeData.skills} />
  <Experience experience={resumeData.experience} />
  <Education education={resumeData.education} />
</main>

// src/App.jsx
import React from 'react';
import Header from './components/Header';
import Profile from './components/Profile';
import Skills from './components/Skills';
import Experience from './components/Experience';
import Education from './components/Education';
import Footer from './components/Footer';
import resumeData from './resumeData.json';

function App() {
  const { name, title, contact, summary, skills, experience, education, author, year, license } = resumeData;

  return (
    <>
      <Header name={name} title={title} contact={contact} />
      <Profile summary={summary} />
      <Skills skills={skills} />
      <Experience experience={experience} />
      <Education education={education} />
      <Footer author={author} year={year} license={license}/>
    </>
  );
}

export default App;
